services:
  tunegrabber:
    container_name: tunegrabber
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
      - "5000:5000"
    environment:
      - SPOTIFY_SECRET=
      - SPOTIFY_CLIENT_ID=